import os
import json
import asyncio
import logging
import re
import threading
import time as _time
import redis
import yt_dlp
from pathlib import Path
from datetime import date
from flask import Flask
from pyrogram import Client, filters
from pyrogram.types import (
    Message,
    InlineKeyboardMarkup,
    InlineKeyboardButton,
    CallbackQuery,
    InlineQuery,
    InlineQueryResultArticle,
    InputTextMessageContent,
    InputMediaPhoto,
    InputMediaVideo,
)
from pyrogram.enums import ChatType, ChatMemberStatus

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

BOT_TOKEN = os.getenv("BOT_TOKEN")
API_ID = int(os.getenv("API_ID", "0"))
API_HASH = os.getenv("API_HASH")
ADMIN_ID = int(os.getenv("ADMIN_ID", "0"))
REDIS_URL = os.getenv("REDIS_URL")
CHANNEL_ID = os.getenv("CHANNEL_ID", "")
INSTAGRAM_SESSION = os.getenv("INSTAGRAM_SESSION", "")  # Instagram sessionid cookie  # Kanal username: @channel_name yoki ID
YOUTUBE_COOKIES = os.getenv("YOUTUBE_COOKIES", "")  # YouTube cookies.txt (Netscape format) — blokdan qochish uchun

if not BOT_TOKEN or not API_ID or not API_HASH:
    raise ValueError("BOT_TOKEN, API_ID va API_HASH environment variable lar o'rnatilishi shart!")

# Redis ulanishi
r = None
if REDIS_URL:
    try:
        r = redis.from_url(REDIS_URL, decode_responses=True)
        r.ping()
        logger.info("✅ Redis ga ulandi")
    except Exception as e:
        logger.warning(f"⚠️ Redis ga ulanib bo'lmadi: {e}")
        r = None

app = Client("instabot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)

DOWNLOAD_DIR = Path("downloads")
DOWNLOAD_DIR.mkdir(exist_ok=True)

# URL xotira — callback_data 64 bayt limiti uchun
pending_urls = {}  # {msg_id: url}

# Xotira sizib chiqishining oldini olish — kuzatiladigan yozuvlar soni cheklanadi
_MAX_TRACKED = 2000


def _remember(d: dict, key, value):
    """dict ga yozadi va o'lcham oshib ketsa eng eski yozuvlarni o'chiradi"""
    d[key] = value
    if len(d) > _MAX_TRACKED:
        for k in list(d.keys())[: len(d) - _MAX_TRACKED]:
            d.pop(k, None)


def _md_escape(s) -> str:
    """Pyrogram Markdown maxsus belgilarini escape qilish.
    Qo'shiq/track nomlaridagi *, _, [, ] kabi belgilar xabarni buzmasligi uchun."""
    if not s:
        return ""
    s = str(s)
    for ch in ("\\", "`", "*", "_", "~", "[", "]", "|"):
        s = s.replace(ch, "\\" + ch)
    return s

# Instagram cookie fayl yaratish
COOKIE_FILE = Path("instagram_cookies.txt")

def _create_cookie_file():
    """Instagram session cookie ni Netscape formatda fayl qilib yaratish"""
    if not INSTAGRAM_SESSION:
        return None
    # sessionid dan ds_user_id ajratish (format: userid%3Atoken...)
    ds_user_id = ""
    try:
        ds_user_id = INSTAGRAM_SESSION.split("%3A")[0]
    except Exception:
        pass
    cookie_content = (
        "# Netscape HTTP Cookie File\n"
        "# https://curl.haxx.se/rfc/cookie_spec.html\n"
        "# This file was generated by bot\n\n"
        f".instagram.com\tTRUE\t/\tTRUE\t0\tsessionid\t{INSTAGRAM_SESSION}\n"
    )
    if ds_user_id:
        cookie_content += f".instagram.com\tTRUE\t/\tTRUE\t0\tds_user_id\t{ds_user_id}\n"
    COOKIE_FILE.write_text(cookie_content)
    return str(COOKIE_FILE)

# Bot ishga tushganda cookie yaratish
_cookie_path = _create_cookie_file()
if _cookie_path:
    logger.info("✅ Instagram cookie fayl yaratildi")
else:
    logger.warning("⚠️ INSTAGRAM_SESSION o'rnatilmagan — cookie siz ishlaydi")

# YouTube cookie fayl yaratish (qo'shiq yuklashda blokdan qochish uchun)
YT_COOKIE_FILE = Path("youtube_cookies.txt")


def _create_youtube_cookie_file():
    """YOUTUBE_COOKIES env (Netscape cookies.txt matni) ni faylga yozish.
    Qaytaradi: (path, cookie_line_count) yoki (None, 0)."""
    if not YOUTUBE_COOKIES:
        return None, 0
    content = YOUTUBE_COOKIES
    # \n literal kelgan bo'lsa haqiqiy newline ga aylantirish
    content = content.replace("\\n", "\n").replace("\\t", "\t")
    # Netscape header bo'lmasa qo'shamiz
    if not content.lstrip().startswith("# Netscape"):
        content = "# Netscape HTTP Cookie File\n" + content
    YT_COOKIE_FILE.write_text(content)
    # Diagnostika: nechta haqiqiy cookie qatori bor (izoh va bo'sh qatorlardan tashqari)
    cookie_lines = [
        ln for ln in content.splitlines()
        if ln.strip() and not ln.lstrip().startswith("#")
    ]
    return str(YT_COOKIE_FILE), len(cookie_lines)


_yt_cookie_path, _yt_cookie_count = _create_youtube_cookie_file()
if _yt_cookie_path:
    logger.info(f"✅ YouTube cookie fayl yaratildi — {_yt_cookie_count} ta cookie qatori")
    if _yt_cookie_count < 3:
        logger.warning(
            "⚠️ YouTube cookie qatorlari juda kam! "
            "Render env'ga cookie'lar bir qatorga yopishib tushgan bo'lishi mumkin "
            "(yangi qatorlar yo'qolgan). cookies.txt to'liq, qatorma-qator joylanganiga ishonch hosil qiling."
        )
else:
    logger.warning("⚠️ YOUTUBE_COOKIES o'rnatilmagan — YouTube cookie siz ishlaydi")

# Flask keep-alive
flask_app = Flask(__name__)


@flask_app.route("/")
def home():
    return "Bot ishlayapti ✅"


def run_flask():
    port = int(os.environ.get("PORT", 8080))
    flask_app.run(host="0.0.0.0", port=port)


# ═══════════════════════════════════════════════════════════
# 🌐 KO'P TILLI TIZIM (i18n)
# ═══════════════════════════════════════════════════════════

TEXTS = {
    "uz": {
        "start": (
            "👋 Salom, **{name}**!\n\n"
            "📥 Men **Instagram Saver** botman.\n\n"
            "📌 Nima yuklay olaman:\n"
            "• 🎬 Reels (video/audio)\n"
            "• 🖼 Postlar (rasm/video)\n"
            "• 📖 Stories\n\n"
            "🎯 **Buyruqlar:**\n"
            "• /favorites — Sevimlilar\n"
            "• /help — Qo'llanma\n"
            "• /lang — Tilni o'zgartirish\n\n"
            "➡️ Instagram havolasini yuboring!"
        ),
        "help": (
            "📖 **Qo'llanma:**\n\n"
            "1️⃣ Instagram da post/reel/story ni oching\n"
            "2️⃣ Havolasini nusxalang\n"
            "3️⃣ Menga yuboring\n"
            "4️⃣ Yuklanib keladi ✅\n\n"
            "💡 **Qo'shimcha:**\n"
            "• Rasm bo'lsa — avtomatik yuklab beradi\n"
            "• Video bo'lsa — Video/Audio tanlash mumkin\n"
            "• Carousel — barcha rasmlar yuklanadi\n"
            "• /favorites — sevimlilar ro'yxati\n"
            "• /lang — tilni o'zgartirish\n\n"
            "⚠️ **Ishlamaydi:**\n"
            "• Private akkaunt postlari\n"
            "• O'chirilgan postlar\n\n"
            "📩 **Talab va takliflar:** @theSarvar_04"
        ),
        "lang_choose": "🌐 **Tilni tanlang / Choose language / Выберите язык:**",
        "lang_set": "✅ Til o'zgartirildi: **O'zbekcha** 🇺🇿",
        "send_link": "📎 Instagram havolasini yuboring.",
        "only_insta_tiktok": "⚠️ Faqat **Instagram** havolalarini qabul qilaman.",
        "favorites_empty": "⭐ **Sevimlilar ro'yxati bo'sh.**\n\nHavola yuboring va \"⭐\" tugmasini bosing!",
        "favorites_title": "⭐ **Sevimlilar:**\n\n",
        "downloading": "⬇️ Yuklab olinmoqda...",
        "downloaded": "📥 Yuklandi",
        "download_error": "❌ Yuklab bo'lmadi.",
        "private_error": "❌ Bu post xususiy (private).",
        "login_error": "❌ Login talab qilmoqda.",
        "not_found_error": "❌ Post mavjud emas yoki o'chirilgan.",
        "audio_extracting": "🎵 Audio ajratilmoqda...",
        "audio_done": "🎵 Yuklandi",
        "btn_find_song": "🔍 Qo'shiqni topish",
        "song_recognizing": "🔍 Qo'shiq aniqlanmoqda...",
        "song_not_found": "❌ Qo'shiq aniqlanmadi. Videoda taniqli musiqa topilmadi.",
        "song_recognized": "🎵 Topildi: **{name}**\n\n⬇️ Variantlar qidirilmoqda...",
        "song_choose": "🎵 **{name}**\n\n👇 Quyidagi variantlardan birini raqamli tugma (1-5) orqali tanlang:",
        "song_no_results": "❌ SoundCloud'dan variant topilmadi.",
        "song_downloading": "⬇️ Tanlangan qo'shiq yuklab olinmoqda...",
        "song_expired": "⚠️ Variantlar eskirdi. Qaytadan \"🔍 Qo'shiqni topish\" ni bosing.",
        "subscribe_channel": "❗ Botdan foydalanish uchun kanalga obuna bo'ling:\n\n👉 {channel}\n\n✅ Obuna bo'lgach, qayta yuboring.",
        "speed_text": "⚡ {seconds} soniyada yuklandi",
        "stats_text": (
            "📊 **Bot statistikasi:**\n\n"
            "👥 Jami: **{total}** ta\n"
            "📅 Bugun: **{today}** ta\n"
            "🚫 Bloklangan: **{banned}** ta"
        ),
        "broadcast_start": "📢 Broadcast boshlandi...",
        "broadcast_done": "✅ Broadcast tugadi.\n\n📨 Yuborildi: **{sent}**\n❌ Xato: **{failed}**",
        "user_banned": "🚫 Foydalanuvchi bloklandi: `{uid}`",
        "user_unbanned": "✅ Foydalanuvchi blokdan chiqarildi: `{uid}`",
        "banned_msg": "⛔ Siz bloklangansiz. Admin: @theSarvar_04",
        "admin_only": "⛔ Bu buyruq faqat admin uchun.",
        "btn_favorite": "⭐ Sevimlilarga",
        "btn_audio": "🎵 Audio yuklab olish",
        "caption": "📥 {platform} dan yuklandi\n@InstaDownloader_uzBot",
        "caption_speed": "📥 {platform} dan yuklandi | ⚡ {seconds}s\n@InstaDownloader_uzBot",
    },
    "en": {
        "start": (
            "👋 Hello, **{name}**!\n\n"
            "📥 I'm an **Instagram Saver** bot.\n\n"
            "📌 What I can download:\n"
            "• 🎬 Instagram Reels (video/audio)\n"
            "• 🖼 Instagram Posts (photo/video)\n"
            "• 📖 Instagram Stories\n\n"
            "🎯 **Commands:**\n"
            "• /favorites — Favorites\n"
            "• /help — Guide\n"
            "• /lang — Change language\n\n"
            "➡️ Send an Instagram link!"
        ),
        "help": (
            "📖 **Guide:**\n\n"
            "1️⃣ Open a post/reel/story on Instagram\n"
            "2️⃣ Copy the link\n"
            "3️⃣ Send it to me\n"
            "4️⃣ Download will be ready ✅\n\n"
            "💡 **Extra:**\n"
            "• Photos — auto downloaded\n"
            "• Videos — Video/Audio options\n"
            "• Carousel — all images downloaded\n"
            "• /favorites — favorites list\n"
            "• /lang — change language\n\n"
            "⚠️ **Doesn't work:**\n"
            "• Private account posts\n"
            "• Deleted posts\n\n"
            "📩 **Feedback:** @theSarvar_04"
        ),
        "lang_choose": "🌐 **Tilni tanlang / Choose language / Выберите язык:**",
        "lang_set": "✅ Language changed: **English** 🇬🇧",
        "send_link": "📎 Send an Instagram link.",
        "only_insta_tiktok": "⚠️ I only accept **Instagram** links.",
        "favorites_empty": "⭐ **Favorites list is empty.**\n\nSend a link and tap the \"⭐\" button!",
        "favorites_title": "⭐ **Favorites:**\n\n",
        "downloading": "⬇️ Downloading...",
        "downloaded": "📥 Downloaded",
        "download_error": "❌ Download failed.",
        "private_error": "❌ This post is private.",
        "login_error": "❌ Login required.",
        "not_found_error": "❌ Post not found or deleted.",
        "audio_extracting": "🎵 Extracting audio...",
        "audio_done": "🎵 Downloaded",
        "btn_find_song": "🔍 Find the song",
        "song_recognizing": "🔍 Recognizing the song...",
        "song_not_found": "❌ Couldn't recognize the song. No known music found in the video.",
        "song_recognized": "🎵 Found: **{name}**\n\n⬇️ Searching for options...",
        "song_choose": "🎵 **{name}**\n\n👇 Pick one of the options using the number buttons (1-5):",
        "song_no_results": "❌ No options found on SoundCloud.",
        "song_downloading": "⬇️ Downloading the selected song...",
        "song_expired": "⚠️ The options expired. Tap \"🔍 Find the song\" again.",
        "subscribe_channel": "❗ Subscribe to the channel to use the bot:\n\n👉 {channel}\n\n✅ After subscribing, send again.",
        "speed_text": "⚡ Downloaded in {seconds}s",
        "stats_text": (
            "📊 **Bot Statistics:**\n\n"
            "👥 Total: **{total}**\n"
            "📅 Today: **{today}**\n"
            "🚫 Banned: **{banned}**"
        ),
        "broadcast_start": "📢 Broadcast started...",
        "broadcast_done": "✅ Broadcast done.\n\n📨 Sent: **{sent}**\n❌ Failed: **{failed}**",
        "user_banned": "🚫 User banned: `{uid}`",
        "user_unbanned": "✅ User unbanned: `{uid}`",
        "banned_msg": "⛔ You are banned. Admin: @theSarvar_04",
        "admin_only": "⛔ This command is for admin only.",
        "btn_favorite": "⭐ Favorite",
        "btn_audio": "🎵 Download audio",
        "caption": "📥 Downloaded from {platform}\n@InstaDownloader_uzBot",
        "caption_speed": "📥 Downloaded from {platform} | ⚡ {seconds}s\n@InstaDownloader_uzBot",
    },
    "ru": {
        "start": (
            "👋 Привет, **{name}**!\n\n"
            "📥 Я бот **Instagram Saver**.\n\n"
            "📌 Что я могу скачать:\n"
            "• 🎬 Instagram Reels (видео/аудио)\n"
            "• 🖼 Instagram Посты (фото/видео)\n"
            "• 📖 Instagram Stories\n\n"
            "🎯 **Команды:**\n"
            "• /favorites — Избранное\n"
            "• /help — Инструкция\n"
            "• /lang — Сменить язык\n\n"
            "➡️ Отправьте ссылку Instagram!"
        ),
        "help": (
            "📖 **Инструкция:**\n\n"
            "1️⃣ Откройте пост/рилс/сторис в Instagram\n"
            "2️⃣ Скопируйте ссылку\n"
            "3️⃣ Отправьте мне\n"
            "4️⃣ Скачается ✅\n\n"
            "💡 **Дополнительно:**\n"
            "• Фото — автоматически скачивается\n"
            "• Видео — выбор Видео/Аудио\n"
            "• Карусель — все фото скачиваются\n"
            "• /favorites — список избранного\n"
            "• /lang — сменить язык\n\n"
            "⚠️ **Не работает:**\n"
            "• Посты приватных аккаунтов\n"
            "• Удалённые посты\n\n"
            "📩 **Обратная связь:** @theSarvar_04"
        ),
        "lang_choose": "🌐 **Tilni tanlang / Choose language / Выберите язык:**",
        "lang_set": "✅ Язык изменён: **Русский** 🇷🇺",
        "send_link": "📎 Отправьте ссылку Instagram.",
        "only_insta_tiktok": "⚠️ Я принимаю только ссылки **Instagram**.",
        "favorites_empty": "⭐ **Список избранного пуст.**\n\nОтправьте ссылку и нажмите \"⭐\"!",
        "favorites_title": "⭐ **Избранное:**\n\n",
        "downloading": "⬇️ Скачиваю...",
        "downloaded": "📥 Скачано",
        "download_error": "❌ Не удалось скачать.",
        "private_error": "❌ Этот пост приватный.",
        "login_error": "❌ Требуется авторизация.",
        "not_found_error": "❌ Пост не найден или удалён.",
        "audio_extracting": "🎵 Извлекаю аудио...",
        "audio_done": "🎵 Скачано",
        "btn_find_song": "🔍 Найти песню",
        "song_recognizing": "🔍 Распознаю песню...",
        "song_not_found": "❌ Не удалось распознать песню. В видео не найдена известная музыка.",
        "song_recognized": "🎵 Найдено: **{name}**\n\n⬇️ Ищу варианты...",
        "song_choose": "🎵 **{name}**\n\n👇 Выберите вариант с помощью кнопок с номерами (1-5):",
        "song_no_results": "❌ Варианты не найдены на SoundCloud.",
        "song_downloading": "⬇️ Скачиваю выбранную песню...",
        "song_expired": "⚠️ Варианты устарели. Нажмите \"🔍 Найти песню\" снова.",
        "subscribe_channel": "❗ Подпишитесь на канал, чтобы использовать бота:\n\n👉 {channel}\n\n✅ После подписки отправьте снова.",
        "speed_text": "⚡ Скачано за {seconds}с",
        "stats_text": (
            "📊 **Статистика бота:**\n\n"
            "👥 Всего: **{total}**\n"
            "📅 Сегодня: **{today}**\n"
            "🚫 Забанено: **{banned}**"
        ),
        "broadcast_start": "📢 Рассылка началась...",
        "broadcast_done": "✅ Рассылка завершена.\n\n📨 Отправлено: **{sent}**\n❌ Ошибки: **{failed}**",
        "user_banned": "🚫 Пользователь заблокирован: `{uid}`",
        "user_unbanned": "✅ Пользователь разблокирован: `{uid}`",
        "banned_msg": "⛔ Вы заблокированы. Админ: @theSarvar_04",
        "admin_only": "⛔ Эта команда только для админа.",
        "btn_favorite": "⭐ В избранное",
        "btn_audio": "🎵 Скачать аудио",
        "caption": "📥 Скачано из {platform}\n@InstaDownloader_uzBot",
        "caption_speed": "📥 Скачано из {platform} | ⚡ {seconds}с\n@InstaDownloader_uzBot",
    },
}


def get_user_lang(user_id: int) -> str:
    if r:
        lang = r.get(f"lang:{user_id}")
        if lang and lang in TEXTS:
            return lang
    return "uz"


def set_user_lang(user_id: int, lang: str):
    if r:
        r.set(f"lang:{user_id}", lang)


def t(user_id: int, key: str, **kwargs) -> str:
    lang = get_user_lang(user_id)
    text = TEXTS.get(lang, TEXTS["uz"]).get(key, TEXTS["uz"].get(key, ""))
    if kwargs:
        return text.format(**kwargs)
    return text


# ═══════════════════════════════════════════════════════════
# 📊 REDIS YORDAMCHI FUNKSIYALAR
# ═══════════════════════════════════════════════════════════

def save_user(user_id: int):
    if not r:
        return
    today = str(date.today())
    uid = str(user_id)
    r.sadd("users:all", uid)
    r.sadd(f"users:date:{today}", uid)


def get_stats() -> dict:
    if not r:
        return {"total": 0, "today": 0, "banned": 0}
    today = str(date.today())
    total = r.scard("users:all") or 0
    today_count = r.scard(f"users:date:{today}") or 0
    banned = r.scard("users:banned") or 0
    return {"total": total, "today": today_count, "banned": banned}


def is_banned(user_id: int) -> bool:
    if not r:
        return False
    return r.sismember("users:banned", str(user_id))


def ban_user(user_id: int):
    if r:
        r.sadd("users:banned", str(user_id))


def unban_user(user_id: int):
    if r:
        r.srem("users:banned", str(user_id))


def get_all_users() -> list:
    if not r:
        return []
    return list(r.smembers("users:all"))


# ═══════════════════════════════════════════════════════════
# 💾 CACHE TIZIMI
# ═══════════════════════════════════════════════════════════

CACHE_TTL = 86400 * 7


def get_cache(url: str, mode: str):
    if not r:
        return None
    key = f"cache:{mode}:{url}"
    data = r.get(key)
    if data:
        return json.loads(data)
    return None


def set_cache(url: str, mode: str, file_data: dict):
    if not r:
        return
    key = f"cache:{mode}:{url}"
    r.setex(key, CACHE_TTL, json.dumps(file_data))


# ═══════════════════════════════════════════════════════════
# ⭐ SEVIMLILAR
# ═══════════════════════════════════════════════════════════

MAX_FAVORITES = 10


def add_favorite(user_id: int, url: str):
    if not r:
        return
    key = f"favorites:{user_id}"
    existing = r.lrange(key, 0, -1)
    if url in existing:
        return
    r.lpush(key, url)
    r.ltrim(key, 0, MAX_FAVORITES - 1)


def get_favorites(user_id: int) -> list:
    if not r:
        return []
    key = f"favorites:{user_id}"
    return r.lrange(key, 0, MAX_FAVORITES - 1)


# ═══════════════════════════════════════════════════════════
# 🔗 HAVOLA ANIQLAGICH
# ═══════════════════════════════════════════════════════════

def extract_instagram_url(text: str) -> str | None:
    pattern = r'https?://(?:www\.)?(?:instagram\.com|instagr\.am)/(?:p|reel|reels|tv|stories)/[^\s\'"<>]+'
    match = re.search(pattern, text)
    return match.group(0) if match else None


def extract_any_url(text: str) -> tuple[str | None, str]:
    """Returns (url, platform)"""
    url = extract_instagram_url(text)
    if url:
        return url, "Instagram"
    return None, ""


# ═══════════════════════════════════════════════════════════
# 🔔 KANAL OBUNA TEKSHIRISH
# ═══════════════════════════════════════════════════════════

async def check_subscription(client, user_id: int) -> bool:
    """Foydalanuvchi kanalga obuna bo'lganligini tekshirish"""
    if not CHANNEL_ID:
        return True  # Kanal sozlanmagan — tekshirish o'tkazilmaydi
    try:
        member = await client.get_chat_member(CHANNEL_ID, user_id)
        return member.status in [
            ChatMemberStatus.MEMBER,
            ChatMemberStatus.ADMINISTRATOR,
            ChatMemberStatus.OWNER,
        ]
    except Exception:
        return True  # Xatolik bo'lsa — o'tkazib yuboramiz


# ═══════════════════════════════════════════════════════════
# ⬇️ YUKLAB OLISH FUNKSIYALARI
# ═══════════════════════════════════════════════════════════

async def download_video(url: str, chat_id: int):
    output_template = str(DOWNLOAD_DIR / f"{chat_id}_%(title).40s.%(ext)s")
    ydl_opts = {
        "outtmpl": output_template,
        # H.264 (avc) kodekni afzal ko'rish — Telegram telefon pleyeri uchun
        "format": (
            "bestvideo[ext=mp4][vcodec^=avc1]+bestaudio[ext=m4a]/"
            "best[ext=mp4][vcodec^=avc1]/"
            "best[ext=mp4]/best"
        ),
        "merge_output_format": "mp4",
        "quiet": True,
        "no_warnings": True,
        "socket_timeout": 30,
        "postprocessor_args": {
            "merger": ["-c", "copy", "-movflags", "+faststart"]
        },
    }
    if _cookie_path:
        ydl_opts["cookiefile"] = _cookie_path
    return await _execute_download(url, chat_id, ydl_opts)


async def download_photo(url: str, chat_id: int):
    """Rasmni yuklab olish — instaloader orqali"""
    try:
        loop = asyncio.get_running_loop()

        def _download_with_instaloader():
            import instaloader
            import urllib.request

            L = instaloader.Instaloader(quiet=True)
            # Session cookie bilan login (agar mavjud bo'lsa)
            if INSTAGRAM_SESSION:
                try:
                    L.context._session.cookies.set("sessionid", INSTAGRAM_SESSION, domain=".instagram.com")
                    ds_uid = INSTAGRAM_SESSION.split("%3A")[0] if "%3A" in INSTAGRAM_SESSION else ""
                    if ds_uid:
                        L.context._session.cookies.set("ds_user_id", ds_uid, domain=".instagram.com")
                except Exception:
                    pass
            match = re.search(r'/(?:p|reel|reels|tv)/([A-Za-z0-9_-]+)', url)
            if not match:
                return None

            shortcode = match.group(1)
            try:
                post = instaloader.Post.from_shortcode(L.context, shortcode)
            except Exception:
                return None

            downloaded = []

            if post.typename == 'GraphSidecar':
                for i, node in enumerate(post.get_sidecar_nodes()):
                    if not node.is_video:
                        img_url = node.display_url
                        filepath = DOWNLOAD_DIR / f"{chat_id}_photo_{i}.jpg"
                        urllib.request.urlretrieve(img_url, str(filepath))
                        downloaded.append(filepath)
                    else:
                        # Carousel dagi video
                        vid_url = node.video_url
                        filepath = DOWNLOAD_DIR / f"{chat_id}_video_{i}.mp4"
                        urllib.request.urlretrieve(vid_url, str(filepath))
                        downloaded.append(filepath)
            else:
                if not post.is_video:
                    img_url = post.url
                    filepath = DOWNLOAD_DIR / f"{chat_id}_photo_0.jpg"
                    urllib.request.urlretrieve(img_url, str(filepath))
                    downloaded.append(filepath)

            return downloaded

        files = await loop.run_in_executor(None, _download_with_instaloader)

        if files:
            return files, None
        return None, "❌ Rasm topilmadi."

    except Exception as e:
        err = str(e).lower()
        if "private" in err or "login" in err:
            return None, "private"
        return None, f"❌ Yuklab bo'lmadi: `{str(e)[:100]}`"


async def _execute_download(url: str, chat_id: int, ydl_opts: dict):
    try:
        loop = asyncio.get_running_loop()

        def _download():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.extract_info(url, download=True)

        await loop.run_in_executor(None, _download)

        files = [f for f in DOWNLOAD_DIR.iterdir() if f.name.startswith(f"{chat_id}_")]
        if files:
            return files, None
        return None, "not_found"

    except yt_dlp.utils.DownloadError as e:
        err = str(e).lower()
        if "private" in err:
            return None, "private"
        elif "login" in err or "sign in" in err or "cookie" in err:
            return None, "login"
        elif "not available" in err or "removed" in err:
            return None, "not_found"
        else:
            return None, f"❌ `{str(e)[:120]}`"
    except Exception as e:
        return None, f"❌ `{str(e)[:120]}`"


def cleanup(chat_id: int):
    for f in DOWNLOAD_DIR.iterdir():
        if f.name.startswith(f"{chat_id}_"):
            try:
                f.unlink()
            except Exception:
                pass


def get_error_text(user_id: int, error: str) -> str:
    if error == "private":
        return t(user_id, "private_error")
    elif error == "login":
        return t(user_id, "login_error")
    elif error == "not_found":
        return t(user_id, "not_found_error")
    elif error.startswith("❌"):
        return error
    return t(user_id, "download_error")


async def send_media_files(message, files, caption, uid, msg_id, url):
    """Fayllarni yuborish:
    - Bitta fayl bo'lsa — tugmalar bilan oddiy yuboradi
    - Bir nechta bo'lsa — media group (albom) qilib bittada yuboradi, keyin tugma alohida
    """
    PHOTO_EXTS = {".jpg", ".jpeg", ".png", ".webp"}
    VIDEO_EXTS = {".mp4", ".mov", ".mkv", ".webm"}

    media_files = [f for f in files if f.suffix.lower() in (PHOTO_EXTS | VIDEO_EXTS)]
    other_files = [f for f in files if f.suffix.lower() not in (PHOTO_EXTS | VIDEO_EXTS)]

    # ─── Bir nechta media — ALBOM qilib yuborish ───
    if len(media_files) > 1:
        media_group = []
        for i, filepath in enumerate(media_files[:10]):  # Telegram limit: 10 ta
            ext = filepath.suffix.lower()
            cap = caption if i == 0 else None  # Faqat birinchisida caption
            if ext in PHOTO_EXTS:
                media_group.append(InputMediaPhoto(str(filepath), caption=cap))
            else:
                media_group.append(InputMediaVideo(str(filepath), caption=cap, supports_streaming=True))

        try:
            await message.reply_media_group(media_group)
            # Albomdan keyin tugmalarni alohida xabar bilan yuborish
            has_video = any(f.suffix.lower() in VIDEO_EXTS for f in media_files)
            buttons = [[InlineKeyboardButton(t(uid, "btn_favorite"), callback_data=f"fav|{msg_id}")]]
            if has_video:
                buttons.append([InlineKeyboardButton(t(uid, "btn_find_song"), callback_data=f"findsong|{msg_id}")])
            await message.reply(
                "✅ " + str(len(media_files)) + " ta media yuklandi\n@InstaDownloader_uzBot",
                reply_markup=InlineKeyboardMarkup(buttons)
            )
        except Exception:
            # Albom ishlamasa — bitta-bitta yuborish
            for filepath in media_files:
                ext = filepath.suffix.lower()
                if ext in PHOTO_EXTS:
                    await message.reply_photo(str(filepath), caption=caption)
                else:
                    await message.reply_video(str(filepath), caption=caption, supports_streaming=True)
        # Boshqa fayllar (agar bo'lsa)
        for filepath in other_files:
            await message.reply_document(str(filepath), caption=caption)
        return

    # ─── Bitta media — oddiy yuborish (tugmalar bilan) ───
    for filepath in files:
        ext = filepath.suffix.lower()
        if ext in VIDEO_EXTS:
            try:
                sent = await message.reply_video(
                    str(filepath),
                    caption=caption,
                    supports_streaming=True,
                    reply_markup=InlineKeyboardMarkup([
                        [InlineKeyboardButton(t(uid, "btn_favorite"), callback_data=f"fav|{msg_id}")],
                        [InlineKeyboardButton(t(uid, "btn_find_song"), callback_data=f"findsong|{msg_id}")]
                    ])
                )
                set_cache(url, "video", {"type": "video", "file_id": sent.video.file_id})
            except Exception:
                sent = await message.reply_document(
                    str(filepath),
                    caption=caption,
                    reply_markup=InlineKeyboardMarkup([
                        [InlineKeyboardButton(t(uid, "btn_favorite"), callback_data=f"fav|{msg_id}")],
                        [InlineKeyboardButton(t(uid, "btn_find_song"), callback_data=f"findsong|{msg_id}")]
                    ])
                )
                set_cache(url, "video", {"type": "document", "file_id": sent.document.file_id})
        elif ext in PHOTO_EXTS:
            try:
                sent = await message.reply_photo(
                    str(filepath),
                    caption=caption,
                    reply_markup=InlineKeyboardMarkup([
                        [InlineKeyboardButton(t(uid, "btn_favorite"), callback_data=f"fav|{msg_id}")]
                    ])
                )
                set_cache(url, "photo", {"type": "photo", "file_id": sent.photo.file_id})
            except Exception:
                await message.reply_document(str(filepath), caption=caption)
        else:
            await message.reply_document(str(filepath), caption=caption)


# ═══════════════════════════════════════════════════════════
# 🤖 BOT KOMANDALAR
# ═══════════════════════════════════════════════════════════

@app.on_message(filters.command("start"))
async def cmd_start(client, message: Message):
    user = message.from_user
    save_user(user.id)

    # Birinchi marta — til tanlash
    if r and not r.get(f"lang:{user.id}"):
        await message.reply(
            "🌐 **Tilni tanlang / Choose language / Выберите язык:**",
            reply_markup=InlineKeyboardMarkup([
                [
                    InlineKeyboardButton("🇺🇿 O'zbekcha", callback_data="startlang|uz"),
                    InlineKeyboardButton("🇬🇧 English", callback_data="startlang|en"),
                    InlineKeyboardButton("🇷🇺 Русский", callback_data="startlang|ru"),
                ]
            ])
        )
        return

    await message.reply(t(user.id, "start", name=user.first_name))


@app.on_message(filters.command("help"))
async def cmd_help(client, message: Message):
    await message.reply(t(message.from_user.id, "help"))


@app.on_message(filters.command("lang"))
async def cmd_lang(client, message: Message):
    await message.reply(
        t(message.from_user.id, "lang_choose"),
        reply_markup=InlineKeyboardMarkup([
            [
                InlineKeyboardButton("🇺🇿 O'zbekcha", callback_data="lang|uz"),
                InlineKeyboardButton("🇬🇧 English", callback_data="lang|en"),
                InlineKeyboardButton("🇷🇺 Русский", callback_data="lang|ru"),
            ]
        ])
    )


@app.on_message(filters.command("favorites"))
async def cmd_favorites(client, message: Message):
    uid = message.from_user.id
    favs = get_favorites(uid)

    if not favs:
        await message.reply(t(uid, "favorites_empty"))
        return

    text = t(uid, "favorites_title")
    for i, url in enumerate(favs, 1):
        short = url.split("?")[0]
        text += f"{i}. {short}\n"

    await message.reply(
        text,
        disable_web_page_preview=True,
        reply_markup=InlineKeyboardMarkup([
            [InlineKeyboardButton("🗑 Tozalash / Reset", callback_data="favreset")]
        ])
    )


# ═══════════════════════════════════════════════════════════
# 🛡 ADMIN PANEL
# ═══════════════════════════════════════════════════════════

@app.on_message(filters.command("stats"))
async def cmd_stats(client, message: Message):
    if message.from_user.id != ADMIN_ID:
        await message.reply(t(message.from_user.id, "admin_only"))
        return

    stats = get_stats()
    await message.reply(t(message.from_user.id, "stats_text",
                          total=stats["total"], today=stats["today"], banned=stats["banned"]))


@app.on_message(filters.command("broadcast"))
async def cmd_broadcast(client, message: Message):
    """Admin: barcha foydalanuvchilarga xabar yuborish. /broadcast Xabar matni"""
    if message.from_user.id != ADMIN_ID:
        await message.reply(t(message.from_user.id, "admin_only"))
        return

    text = message.text.replace("/broadcast", "", 1).strip()
    if not text:
        await message.reply("📢 Foydalanish: `/broadcast Xabar matni`")
        return

    users = get_all_users()
    if not users:
        await message.reply("❌ Foydalanuvchilar topilmadi.")
        return

    status = await message.reply(t(message.from_user.id, "broadcast_start"))
    sent = 0
    failed = 0

    for uid in users:
        if is_banned(int(uid)):
            continue
        try:
            await client.send_message(int(uid), text)
            sent += 1
            await asyncio.sleep(0.05)  # flood limitdan qochish
        except Exception:
            failed += 1

    await status.edit_text(t(message.from_user.id, "broadcast_done", sent=sent, failed=failed))


@app.on_message(filters.command("ban"))
async def cmd_ban(client, message: Message):
    """Admin: foydalanuvchini bloklash. /ban user_id"""
    if message.from_user.id != ADMIN_ID:
        await message.reply(t(message.from_user.id, "admin_only"))
        return

    parts = message.text.split()
    if len(parts) < 2:
        await message.reply("Foydalanish: `/ban user_id`")
        return

    try:
        uid = int(parts[1])
        ban_user(uid)
        await message.reply(t(message.from_user.id, "user_banned", uid=uid))
    except ValueError:
        await message.reply("❌ Noto'g'ri user_id.")


@app.on_message(filters.command("unban"))
async def cmd_unban(client, message: Message):
    """Admin: foydalanuvchini blokdan chiqarish. /unban user_id"""
    if message.from_user.id != ADMIN_ID:
        await message.reply(t(message.from_user.id, "admin_only"))
        return

    parts = message.text.split()
    if len(parts) < 2:
        await message.reply("Foydalanish: `/unban user_id`")
        return

    try:
        uid = int(parts[1])
        unban_user(uid)
        await message.reply(t(message.from_user.id, "user_unbanned", uid=uid))
    except ValueError:
        await message.reply("❌ Noto'g'ri user_id.")


# ═══════════════════════════════════════════════════════════
# 📨 ASOSIY XABAR HANDLER
# ═══════════════════════════════════════════════════════════

@app.on_message(filters.text & ~filters.command(["start", "help", "stats", "favorites", "lang", "broadcast", "ban", "unban"]))
async def handle_message(client, message: Message):
    user = message.from_user
    uid = user.id
    text = message.text.strip()
    is_group = message.chat.type in [ChatType.GROUP, ChatType.SUPERGROUP]

    # Bloklangan foydalanuvchi tekshirish
    if is_banned(uid):
        if not is_group:
            await message.reply(t(uid, "banned_msg"))
        return

    # Havola aniqlash
    url, platform = extract_any_url(text)

    if is_group:
        if not url:
            return
    else:
        if not url:
            if text.startswith("http"):
                await message.reply(t(uid, "only_insta_tiktok"))
            else:
                await message.reply(t(uid, "send_link"))
            return

    # Kanal obunasi tekshiruvi (faqat shaxsiy chat, CHANNEL_ID sozlangan bo'lsa)
    if not is_group and CHANNEL_ID and not await check_subscription(client, uid):
        await message.reply(t(uid, "subscribe_channel", channel=CHANNEL_ID))
        return

    save_user(uid)

    # Like reaction
    try:
        await app.send_reaction(message.chat.id, message.id, "❤")
    except Exception:
        pass

    # 💾 CACHE TEKSHIRISH — avval yuklangan bo'lsa darhol yuborish
    cached_video = get_cache(url, "video")
    cached_photo = get_cache(url, "photo")

    if cached_video:
        try:
            if cached_video["type"] == "video":
                await message.reply_video(
                    cached_video["file_id"],
                    caption=t(uid, "caption_speed", platform=platform, seconds="0.1"),
                    supports_streaming=True,
                    reply_markup=InlineKeyboardMarkup([
                        [InlineKeyboardButton(t(uid, "btn_favorite"), callback_data=f"fav|{message.id}")],
                        [InlineKeyboardButton(t(uid, "btn_find_song"), callback_data=f"findsong|{message.id}")]
                    ])
                )
            elif cached_video["type"] == "document":
                await message.reply_document(
                    cached_video["file_id"],
                    caption=t(uid, "caption_speed", platform=platform, seconds="0.1"),
                    reply_markup=InlineKeyboardMarkup([
                        [InlineKeyboardButton(t(uid, "btn_favorite"), callback_data=f"fav|{message.id}")],
                        [InlineKeyboardButton(t(uid, "btn_find_song"), callback_data=f"findsong|{message.id}")]
                    ])
                )
            _remember(pending_urls, message.id, url)
            return
        except Exception:
            pass

    if cached_photo:
        try:
            await message.reply_photo(
                cached_photo["file_id"],
                caption=t(uid, "caption_speed", platform=platform, seconds="0.1"),
                reply_markup=InlineKeyboardMarkup([
                    [InlineKeyboardButton(t(uid, "btn_favorite"), callback_data=f"fav|{message.id}")]
                ])
            )
            _remember(pending_urls, message.id, url)
            return
        except Exception:
            pass

    # Vaqtni boshlash (tezlik uchun)
    start_time = _time.time()

    # 📊 Zamonaviy progress bar
    async def show_progress(status_msg, stage):
        stages = [
            ("🔍", "Link tekshirilmoqda", 10),
            ("📡", "Instagram ga ulanilmoqda", 25),
            ("⬇️", "Yuklab olinmoqda", 50),
            ("🔄", "Qayta ishlanmoqda", 75),
            ("📤", "Telegramga yuborilmoqda", 90),
            ("✅", "Tayyor!", 100),
        ]
        if stage >= len(stages):
            stage = len(stages) - 1
        emoji, text_stage, percent = stages[stage]
        filled = int(percent / 10)
        empty = 10 - filled
        bar = "▰" * filled + "▱" * empty
        elapsed = round(_time.time() - start_time, 1)
        progress_text = (
            f"{emoji} **{text_stage}**\n\n"
            f"{bar}  **{percent}%**\n\n"
            f"⏱ {elapsed} soniya"
        )
        try:
            await status_msg.edit_text(progress_text)
        except Exception:
            pass

    status = await message.reply(
        "🔍 **Link tekshirilmoqda**\n\n"
        "▰▱▱▱▱▱▱▱▱▱  **10%**\n\n"
        "⏱ 0.0 soniya"
    )

    await asyncio.sleep(0.3)
    await show_progress(status, 1)

    # VIDEO yuklab olish
    await asyncio.sleep(0.2)
    await show_progress(status, 2)
    files, error = await download_video(url, message.chat.id)

    # Agar video bo'lmasa — rasm sifatida urinib ko'ramiz (faqat Instagram)
    if error and platform == "Instagram":
        err_str = str(error).lower()
        if "no video" in err_str or "not a video" in err_str or "there is no video" in err_str or error == "not_found":
            cleanup(message.chat.id)
            await show_progress(status, 2)
            files, error = await download_photo(url, message.chat.id)

            if error:
                await status.edit_text(get_error_text(uid, error))
                return

            if not files:
                await status.edit_text(t(uid, "download_error"))
                return

            # Tezlik hisoblash
            elapsed = round(_time.time() - start_time, 1)
            caption = t(uid, "caption_speed", platform=platform, seconds=elapsed)
            await show_progress(status, 4)

            try:
                await send_media_files(message, files, caption, uid, message.id, url)
                _remember(pending_urls, message.id, url)
                await status.delete()
            except Exception as e:
                await status.edit_text(f"❌ `{str(e)[:100]}`")
            finally:
                cleanup(message.chat.id)
            return

    if error:
        await status.edit_text(get_error_text(uid, error))
        return

    if not files:
        await status.edit_text(t(uid, "download_error"))
        return

    # Tezlik hisoblash
    await show_progress(status, 3)
    await asyncio.sleep(0.2)
    await show_progress(status, 4)
    elapsed = round(_time.time() - start_time, 1)
    caption = t(uid, "caption_speed", platform=platform, seconds=elapsed)

    try:
        await send_media_files(message, files, caption, uid, message.id, url)
        _remember(pending_urls, message.id, url)
        await status.delete()

    except Exception as e:
        await status.edit_text(f"❌ `{str(e)[:100]}`")
    finally:
        cleanup(message.chat.id)


# ═══════════════════════════════════════════════════════════
# 🔘 CALLBACK HANDLERS
# ═══════════════════════════════════════════════════════════

@app.on_callback_query(filters.regex(r"^lang\|"))
async def callback_lang(client, callback: CallbackQuery):
    """Til tanlash tugmasi (/lang buyrug'idan)"""
    lang = callback.data.split("|")[1]
    set_user_lang(callback.from_user.id, lang)
    await callback.message.edit_text(t(callback.from_user.id, "lang_set"))


@app.on_callback_query(filters.regex(r"^startlang\|"))
async def callback_startlang(client, callback: CallbackQuery):
    """Birinchi marta /start da til tanlash — keyin start xabari ko'rsatiladi"""
    lang = callback.data.split("|")[1]
    uid = callback.from_user.id
    set_user_lang(uid, lang)
    name = callback.from_user.first_name
    await callback.message.edit_text(t(uid, "start", name=name))


@app.on_callback_query(filters.regex(r"^fav\|"))
async def callback_favorite(client, callback: CallbackQuery):
    msg_id = int(callback.data.split("|")[1])
    user_id = callback.from_user.id
    url = pending_urls.get(msg_id)

    if url:
        add_favorite(user_id, url)
        await callback.answer("⭐", show_alert=False)
    else:
        await callback.answer("⚠️", show_alert=False)


@app.on_callback_query(filters.regex(r"^favreset$"))
async def callback_fav_reset(client, callback: CallbackQuery):
    """Sevimlilar ro'yxatini tozalash"""
    uid = callback.from_user.id
    if r:
        r.delete(f"favorites:{uid}")
    await callback.message.edit_text("✅ Sevimlilar ro'yxati tozalandi.")


# ═══════════════════════════════════════════════════════════
# 🎚 AUDIO EFFEKTLAR (8D, Slowed, Bass, Reverb)
# ═══════════════════════════════════════════════════════════

# FFmpeg filtrlar — sifatli (320kbps)
AUDIO_EFFECTS = {
    "8d": {
        "name": "🎧 8D Audio",
        "filter": "apulsator=hz=0.08",
    },
    "slow": {
        "name": "🐢 Slowed + Reverb",
        "filter": "asetrate=44100*0.85,aresample=44100,aecho=0.8:0.88:60:0.4",
    },
    "bass": {
        "name": "🔊 Bass Boost",
        "filter": "bass=g=12:f=110:w=0.6",
    },
    "reverb": {
        "name": "🏛 Reverb (Concert Hall)",
        "filter": "aecho=0.8:0.9:1000:0.3",
    },
}


# ═══════════════════════════════════════════════════════════
# 🔍 QO'SHIQNI TOPISH (Shazam → YouTube)
# ═══════════════════════════════════════════════════════════

# Topilgan variantlarni vaqtincha saqlash: {msg_id: [{title,url,duration,uploader}, ...]}
song_choices = {}
# Aniqlangan qo'shiq nomini saqlash (SoundCloud zaxira uchun): {msg_id: "Artist - Title"}
song_query = {}


def _format_duration(seconds) -> str:
    """Sekundni mm:ss ko'rinishiga keltirish"""
    try:
        seconds = int(seconds)
        return f"{seconds // 60}:{seconds % 60:02d}"
    except Exception:
        return ""


def _build_song_list_text(uid: int, query: str, results: list) -> str:
    """Variantlarni raqamlangan matn ro'yxati — har biri bitta qatorda.
    Nom va query Markdown'ni buzmasligi uchun escape qilinadi."""
    lines = [t(uid, "song_choose", name=_md_escape(query)), ""]
    for i, res in enumerate(results, 1):
        dur = _format_duration(res.get("duration"))
        title = _md_escape((res.get("title") or "Audio").replace("\n", " ").strip()[:45])
        line = f"**{i}.** {title}"
        if dur:
            line += f" • {dur}"
        lines.append(line)
    return "\n".join(lines)


def _build_song_buttons(results: list, msg_id: int) -> InlineKeyboardMarkup:
    """Faqat raqamli tugmalar (1 2 3 4 5) — bitta qatorda"""
    row = [
        InlineKeyboardButton(str(i + 1), callback_data=f"song|{msg_id}|{i}")
        for i in range(len(results))
    ]
    return InlineKeyboardMarkup([row])


def _song_fx_markup(msg_id: int, index: int) -> InlineKeyboardMarkup:
    """Qo'shiq ostidagi effekt tugmalari (8D / Slowed / Bass / Reverb)"""
    return InlineKeyboardMarkup([
        [
            InlineKeyboardButton("🎧 8D", callback_data=f"fxsong|8d|{msg_id}|{index}"),
            InlineKeyboardButton("🐢 Slowed", callback_data=f"fxsong|slow|{msg_id}|{index}"),
        ],
        [
            InlineKeyboardButton("🔊 Bass", callback_data=f"fxsong|bass|{msg_id}|{index}"),
            InlineKeyboardButton("🏛 Reverb", callback_data=f"fxsong|reverb|{msg_id}|{index}"),
        ],
    ])


async def recognize_song(url: str, chat_id: int):
    """IG havoladan qisqa audio bo'lak olib, Shazam orqali qo'shiqni aniqlash.
    Tezlik uchun: to'liq 320kbps MP3 emas, xom audio yuklanadi va faqat
    birinchi ~15 soniya o'qib olinadi. Qaytaradi: (query_str, error)."""
    loop = asyncio.get_running_loop()

    # 1) Xom audio (qayta kodlashsiz) ni tez yuklab olish
    raw_template = str(DOWNLOAD_DIR / f"{chat_id}_recog.%(ext)s")
    ydl_opts = {
        "outtmpl": raw_template,
        "format": "bestaudio/best",
        "quiet": True,
        "no_warnings": True,
        "socket_timeout": 30,
    }
    if _cookie_path:
        ydl_opts["cookiefile"] = _cookie_path

    def _download_raw():
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.extract_info(url, download=True)
        for f in DOWNLOAD_DIR.iterdir():
            if f.name.startswith(f"{chat_id}_recog."):
                return f
        return None

    try:
        audio_file = await loop.run_in_executor(None, _download_raw)
    except yt_dlp.utils.DownloadError as e:
        err = str(e).lower()
        if "private" in err:
            return None, "private"
        if "login" in err or "sign in" in err:
            return None, "login"
        return None, f"❌ `{str(e)[:100]}`"
    except Exception as e:
        return None, f"❌ `{str(e)[:100]}`"

    if not audio_file:
        return None, "not_found"

    # 2) Faqat birinchi ~15 soniyani past sifatli (mono 16kHz) bo'lakka aylantirish
    snippet = DOWNLOAD_DIR / f"{chat_id}_shazam.ogg"

    def _make_snippet():
        import subprocess
        # "-t 15" ni "-i" dan oldin qo'yamiz — ffmpeg faqat 15s kirishni o'qiydi (tezroq)
        cmd = [
            "ffmpeg", "-y", "-t", "15", "-i", str(audio_file),
            "-vn", "-ac", "1", "-ar", "16000",
            str(snippet),
        ]
        try:
            subprocess.run(cmd, check=True,
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return str(snippet)
        except Exception:
            return str(audio_file)  # bo'lak ajratib bo'lmasa — to'liq audio

    sample_path = await loop.run_in_executor(None, _make_snippet)

    # 3) Shazam orqali aniqlash
    try:
        from shazamio import Shazam
        shazam = Shazam()
        try:
            out = await shazam.recognize(sample_path)  # shazamio >= 0.5
        except (AttributeError, TypeError):
            out = await shazam.recognize_song(sample_path)  # eski versiya

        track = (out or {}).get("track")
        if not track:
            return None, "song_not_found"

        title = (track.get("title") or "").strip()
        artist = (track.get("subtitle") or "").strip()
        if not title:
            return None, "song_not_found"

        query = f"{artist} - {title}" if artist else title
        return query, None
    except ImportError:
        return None, "❌ shazamio o'rnatilmagan."
    except Exception as e:
        return None, f"❌ `{str(e)[:100]}`"


async def search_soundcloud_songs(query: str, limit: int = 5):
    """SoundCloud'dan qo'shiqni qidirib, `limit` ta variant qaytaradi.
    SoundCloud cloud serverlarni bloklamaydi va cookie talab qilmaydi."""
    loop = asyncio.get_running_loop()

    def _search():
        ydl_opts = {
            "quiet": True,
            "no_warnings": True,
            "extract_flat": True,
            "skip_download": True,
            "socket_timeout": 20,
        }
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(f"scsearch{limit}:{query}", download=False)
        entries = (info or {}).get("entries", []) or []
        results = []
        for e in entries:
            if not e:
                continue
            link = e.get("url") or e.get("webpage_url")
            results.append({
                "title": e.get("title") or "Audio",
                "url": link,
                "duration": e.get("duration"),
                "uploader": e.get("uploader") or e.get("uploader_id") or "",
            })
        return [x for x in results if x["url"]]

    try:
        return await loop.run_in_executor(None, _search), None
    except Exception as e:
        return [], f"❌ `{str(e)[:100]}`"


async def download_audio_from_url(url: str, chat_id: int):
    """Berilgan havoladan (SoundCloud va h.k.) to'g'ridan-to'g'ri MP3 (192kbps) yuklab olish.
    SoundCloud bepul treklari ~128kbps, shuning uchun 192 yetarli va tezroq."""
    output_template = str(DOWNLOAD_DIR / f"{chat_id}_song_%(title).40s.%(ext)s")
    ydl_opts = {
        "outtmpl": output_template,
        "format": "bestaudio/best",
        "quiet": True,
        "no_warnings": True,
        "socket_timeout": 30,
        "postprocessors": [{
            "key": "FFmpegExtractAudio",
            "preferredcodec": "mp3",
            "preferredquality": "192",
        }],
    }

    for f in DOWNLOAD_DIR.iterdir():
        if f.name.startswith(f"{chat_id}_song_"):
            try:
                f.unlink()
            except Exception:
                pass

    try:
        loop = asyncio.get_running_loop()

        def _download():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.extract_info(url, download=True)

        await loop.run_in_executor(None, _download)
        files = [f for f in DOWNLOAD_DIR.iterdir()
                 if f.name.startswith(f"{chat_id}_song_")]
        if files:
            return files, None
        return None, "not_found"
    except Exception as e:
        return None, f"❌ `{str(e)[:120]}`"


async def download_song_try_all(results: list, start_index: int, query: str, chat_id: int):
    """Tanlangan variantdan boshlab, yuklab bo'ladiganini topguncha urinadi.
    Ba'zi SoundCloud treklari DRM bilan himoyalangan — ular o'tkazib yuboriladi.
    Qaytaradi: (files, error, used_index)."""
    n = len(results)
    order = [start_index] + [i for i in range(n) if i != start_index]
    last_error = None
    for idx in order:
        url = results[idx].get("url") if 0 <= idx < n else None
        if not url:
            continue
        files, error = await download_audio_from_url(url, chat_id)
        if files:
            return files, None, idx
        last_error = error
    # Hech qaysi variant ishlamasa — nom bo'yicha qayta qidirib ko'ramiz
    if query:
        files, error = await download_song_from_soundcloud(query, chat_id)
        if files:
            return files, None, start_index
        last_error = error or last_error
    return None, last_error, start_index


async def download_song_from_soundcloud(query: str, chat_id: int):
    """SoundCloud'dan qo'shiqni nom bo'yicha qidirib MP3 yuklab olish.
    YouTube serverda bloklanganda zaxira manba sifatida ishlatiladi.
    SoundCloud cookie talab qilmaydi va cloud IP'larni bloklamaydi."""
    output_template = str(DOWNLOAD_DIR / f"{chat_id}_song_%(title).40s.%(ext)s")
    ydl_opts = {
        "outtmpl": output_template,
        "format": "bestaudio/best",
        "quiet": True,
        "no_warnings": True,
        "socket_timeout": 30,
        "default_search": "scsearch",
        "postprocessors": [{
            "key": "FFmpegExtractAudio",
            "preferredcodec": "mp3",
            "preferredquality": "192",
        }],
    }

    # Eski fayllarni tozalash
    for f in DOWNLOAD_DIR.iterdir():
        if f.name.startswith(f"{chat_id}_song_"):
            try:
                f.unlink()
            except Exception:
                pass

    try:
        loop = asyncio.get_running_loop()

        def _download():
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                ydl.extract_info(f"scsearch1:{query}", download=True)

        await loop.run_in_executor(None, _download)
        files = [f for f in DOWNLOAD_DIR.iterdir()
                 if f.name.startswith(f"{chat_id}_song_")]
        if files:
            return files, None
        return None, "not_found"
    except Exception as e:
        return None, f"❌ `{str(e)[:120]}`"


@app.on_callback_query(filters.regex(r"^findsong\|"))
async def callback_find_song(client, callback: CallbackQuery):
    """🔍 Qo'shiqni topish — videodagi musiqani aniqlab, 5 ta variant berish"""
    msg_id = int(callback.data.split("|")[1])
    uid = callback.from_user.id
    chat_id = callback.message.chat.id
    url = pending_urls.get(msg_id)

    if not url:
        await callback.answer("⚠️", show_alert=True)
        return

    await callback.answer("🔍", show_alert=False)

    # ⚡ CACHE: avval aniqlangan bo'lsa — Shazam/qidiruvsiz darhol variantlarni ko'rsatish
    cached_meta = get_cache(url, "songmeta")
    if cached_meta and cached_meta.get("results"):
        c_query = cached_meta.get("query", "")
        c_results = cached_meta["results"]
        _remember(song_choices, msg_id, c_results)
        _remember(song_query, msg_id, c_query)
        try:
            await callback.message.reply(
                _build_song_list_text(uid, c_query, c_results),
                reply_markup=_build_song_buttons(c_results, msg_id)
            )
        except Exception as e:
            await callback.message.reply(f"❌ `{str(e)[:100]}`")
        return

    status = await callback.message.reply(t(uid, "song_recognizing"))

    try:
        # 1) Qo'shiqni aniqlash
        query, error = await recognize_song(url, chat_id)
        if error:
            if error == "song_not_found":
                await status.edit_text(t(uid, "song_not_found"))
            else:
                await status.edit_text(get_error_text(uid, error))
            return
        if not query:
            await status.edit_text(t(uid, "song_not_found"))
            return

        await status.edit_text(t(uid, "song_recognized", name=_md_escape(query)))

        # 2) SoundCloud'dan 5 ta variant qidirish (server IP'dan ishonchli)
        results, serr = await search_soundcloud_songs(query, limit=5)
        if serr or not results:
            await status.edit_text(t(uid, "song_no_results"))
            return

        # 3) Variantlarni saqlash (xotira + Redis kesh) va tugmalar yasash
        _remember(song_choices, msg_id, results)
        _remember(song_query, msg_id, query)
        set_cache(url, "songmeta", {"query": query, "results": results})

        await status.edit_text(
            _build_song_list_text(uid, query, results),
            reply_markup=_build_song_buttons(results, msg_id)
        )
    except Exception as e:
        await status.edit_text(f"❌ `{str(e)[:100]}`")
    finally:
        cleanup(chat_id)


@app.on_callback_query(filters.regex(r"^song\|"))
async def callback_pick_song(client, callback: CallbackQuery):
    """Tanlangan variantni MP3 qilib yuklab berish (4 ta effekt tugmasi bilan)"""
    parts = callback.data.split("|")
    msg_id = int(parts[1])
    index = int(parts[2])
    uid = callback.from_user.id
    chat_id = callback.message.chat.id

    results = song_choices.get(msg_id)
    if not results or index >= len(results):
        await callback.answer("⚠️", show_alert=True)
        try:
            await callback.message.edit_text(t(uid, "song_expired"))
        except Exception:
            pass
        return

    chosen = results[index]
    sc_url = chosen["url"]
    query = song_query.get(msg_id, "")

    # ⚡ CACHE: avval yuklangan bo'lsa — file_id orqali darhol yuborish
    cached_audio = get_cache(sc_url, "scaudio")
    if cached_audio and cached_audio.get("file_id"):
        try:
            await callback.answer("⚡", show_alert=False)
            c_title = cached_audio.get("title") or chosen.get("title") or query or "Audio"
            await callback.message.reply_audio(
                cached_audio["file_id"],
                caption=f"🎵 {_md_escape(c_title)} | ⚡ keshdan | 🟧 SoundCloud\n@InstaDownloader_uzBot",
                title=c_title,
                reply_markup=_song_fx_markup(msg_id, index)
            )
            return
        except Exception:
            pass  # file_id eskirgan bo'lsa — qaytadan yuklaymiz

    await callback.answer("⬇️", show_alert=False)
    status = await callback.message.reply(t(uid, "song_downloading"))

    try:
        start_time = _time.time()
        files, error, used_index = await download_song_try_all(results, index, query, chat_id)

        if not files:
            await status.edit_text(get_error_text(uid, error) if error else t(uid, "download_error"))
            return

        used = results[used_index] if 0 <= used_index < len(results) else chosen
        used_url = used.get("url") or sc_url
        elapsed = round(_time.time() - start_time, 1)
        title = used.get("title") or query or "Audio"

        for filepath in files:
            ext = filepath.suffix.lower()
            if ext in [".mp3", ".m4a", ".ogg", ".wav", ".opus"]:
                sent = await callback.message.reply_audio(
                    str(filepath),
                    caption=f"🎵 {_md_escape(title)} | ⚡ {elapsed}s | 🟧 SoundCloud\n@InstaDownloader_uzBot",
                    title=title,
                    reply_markup=_song_fx_markup(msg_id, used_index)
                )
                # ⚡ file_id ni keshlash — keyingi safar darhol kelishi uchun
                try:
                    if sent and sent.audio:
                        set_cache(used_url, "scaudio", {"file_id": sent.audio.file_id, "title": title})
                except Exception:
                    pass
            else:
                await callback.message.reply_document(
                    str(filepath),
                    caption=f"🎵 {_md_escape(title)}\n@InstaDownloader_uzBot"
                )

        await status.delete()
    except Exception as e:
        await status.edit_text(f"❌ `{str(e)[:100]}`")
    finally:
        cleanup(chat_id)


@app.on_callback_query(filters.regex(r"^fxsong\|"))
async def callback_song_effect(client, callback: CallbackQuery):
    """Topilgan qo'shiqqa effekt qo'shish — 8D / Slowed / Bass / Reverb (YouTube havoladan)"""
    parts = callback.data.split("|")
    effect_key = parts[1]
    msg_id = int(parts[2])
    index = int(parts[3])
    uid = callback.from_user.id
    chat_id = callback.message.chat.id

    results = song_choices.get(msg_id)
    if not results or index >= len(results):
        await callback.answer(t(uid, "song_expired"), show_alert=True)
        return
    query = song_query.get(msg_id, "")

    effect = AUDIO_EFFECTS.get(effect_key)
    if not effect:
        await callback.answer("⚠️", show_alert=True)
        return

    await callback.answer(f"{effect['name']} qo'shilmoqda...", show_alert=False)
    status = await callback.message.reply(f"{effect['name']} qo'shilmoqda...")

    try:
        # SoundCloud havoladan yuklab (DRM bo'lsa boshqa variantga o'tadi), keyin effekt qo'shamiz.
        files, error, _used = await download_song_try_all(results, index, query, chat_id)
        if not files:
            await status.edit_text(get_error_text(uid, error) if error else t(uid, "download_error"))
            return

        loop = asyncio.get_running_loop()

        def _apply_effect():
            import subprocess
            out_files = []
            for src in files:
                if src.suffix.lower() not in [".mp3", ".m4a", ".ogg", ".wav", ".opus"]:
                    continue
                dst = DOWNLOAD_DIR / f"{chat_id}_songfx_{src.stem}.mp3"
                cmd = [
                    "ffmpeg", "-y", "-i", str(src),
                    "-af", effect["filter"],
                    "-b:a", "192k",
                    str(dst),
                ]
                try:
                    subprocess.run(cmd, check=True,
                                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                    try:
                        src.unlink()
                    except Exception:
                        pass
                    out_files.append(dst)
                except Exception:
                    pass
            return out_files

        fx_files = await loop.run_in_executor(None, _apply_effect)
        if not fx_files:
            await status.edit_text("❌ Effekt qo'shib bo'lmadi.")
            return

        for filepath in fx_files:
            await callback.message.reply_audio(
                str(filepath),
                caption=f"{effect['name']}\n@InstaDownloader_uzBot",
                title=effect["name"]
            )

        await status.delete()
    except Exception as e:
        await status.edit_text(f"❌ `{str(e)[:100]}`")
    finally:
        cleanup(chat_id)


# ═══════════════════════════════════════════════════════════
# 🌐 INLINE MODE
# ═══════════════════════════════════════════════════════════

@app.on_inline_query()
async def handle_inline(client, inline_query: InlineQuery):
    """Inline mode — har qanday chatda @botname link yozsa ishlaydi"""
    query = inline_query.query.strip()

    if not query:
        await inline_query.answer(
            results=[
                InlineQueryResultArticle(
                    title="📥 Instagram link yuboring",
                    description="Linkni yozing va natijani tanlang",
                    input_message_content=InputTextMessageContent(
                        "📎 Instagram havolasini yuboring.\n@InstaDownloader_uzBot"
                    ),
                )
            ],
            cache_time=10
        )
        return

    url, platform = extract_any_url(query)

    if url:
        await inline_query.answer(
            results=[
                InlineQueryResultArticle(
                    title=f"📥 {platform} dan yuklab olish",
                    description=url[:60],
                    input_message_content=InputTextMessageContent(url),
                )
            ],
            cache_time=5
        )
    else:
        await inline_query.answer(
            results=[
                InlineQueryResultArticle(
                    title="⚠️ Instagram link kiriting",
                    description="Faqat Instagram havolalari qabul qilinadi",
                    input_message_content=InputTextMessageContent(
                        "⚠️ Faqat Instagram havolalarini qabul qilaman.\n@InstaDownloader_uzBot"
                    ),
                )
            ],
            cache_time=10
        )


# ═══════════════════════════════════════════════════════════
# 🚀 BOTNI ISHGA TUSHIRISH
# ═══════════════════════════════════════════════════════════

async def set_bot_menu():
    """Bot menu (commands) ni sozlash"""
    from pyrogram.types import BotCommand

    commands = [
        BotCommand("start", "Botni ishga tushirish"),
        BotCommand("help", "Qo'llanma"),
        BotCommand("lang", "Tilni o'zgartirish"),
        BotCommand("favorites", "Sevimlilar ro'yxati"),
    ]
    try:
        await app.set_bot_commands(commands)
        logger.info("✅ Bot menu sozlandi")
    except Exception as e:
        logger.warning(f"⚠️ Menu sozlab bo'lmadi: {e}")


if __name__ == "__main__":
    t_flask = threading.Thread(target=run_flask, daemon=True)
    t_flask.start()
    logger.info("✅ Flask server ishga tushdi")

    _time.sleep(1)

    logger.info("✅ InstaBot ishga tushmoqda...")

    async def main():
        await app.start()
        await set_bot_menu()
        logger.info("✅ Bot menu o'rnatildi. Bot ishlayapti...")
        await asyncio.Event().wait()  # Cheksiz kutish

    asyncio.get_event_loop().run_until_complete(main())
